"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l!^1x*7(7&7s#)-ks=ma2==^n^wp#n(@mqg3c7(z9&^w!^orqd'

# SECURITY WARNING: don't run with debug turned on in production!


# AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # for postgres search operator eg ContentEntry.objects.filter(content__search='health')
    'django.contrib.postgres',
    'django.contrib.sitemaps'
]
LOCAL_APPS = [
    'apps.content',
    'apps.util',
    'apps.core',
    'apps.social_share',

]
THIRD_PARTY_APPS = [
    'redactor',
    'mptt',
    'tagging',
    'easy_thumbnails',

]

INSTALLED_APPS += LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, '..', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.get_http_host_name_with_protocol',
                'apps.core.context_processors.get_facebook_app_id',
                'apps.core.context_processors.get_company_name',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
SITE_ID = 1
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'static'),
]
# by default the is a folder saticfiles  created by django, you can create another folder too manually
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'media')
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# print('i am static files finder',STATICFILES_DIRS)
# django-wysiwyg-redactor
REDACTOR_OPTIONS = {'lang': 'en'}
REDACTOR_UPLOAD = 'uploads/'

THUMBNAIL_ALIASES = {
    '': {
        'thumb-820-400': {'size': (800, 400), 'crop': False},
    },
}
COMPANY_NAME = 'Django Simple Blog'
COMPANY_DESCRIPTION = "Django Simple blog system "

HTTP_PROTOCOL = 'https'
HTTP_HOST = 'django-simple-blog.herokuapp.com'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        },

        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['mail_admins', 'console'],
            'propagate': True,
        },

    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#
DEFAULT_FROM_EMAIL = 'bikeshkawang@gmail.com'
SERVER_EMAIL = 'bikeshkawang@gmail.com'
ADMINS = [('bikesh kawan', 'bikeshkawang@gmail.com')]
MANAGERS = ADMINS
GOOGLE_SITE_VERIFICATION = 'hV4EwwprownATbXeq6IZCsdfsd3wEn83E4vAjL0owTzkK4l8'
DISCUSS_URL = 'https://healthmandu.disqus.com/'

FACEBOOK = {'page_link': "http://facebook.com/healthmandu"}
TWITTER = {'page_link': "http://facebook.com/healthmandu"}
GOOGLE = {'page_link': "http://facebook.com/healthmandu"}
