""" Django settings for config project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from .base import *
from .env import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

HTTP_HOST_NAME_WITH_PROTOCOL = 'http://127.0.0.1:8000'
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']

HTTP_HOST_WITH_PROTOCOL = 'http://127.0.0.1:8000'
# for local host
FACEBOOK_APP_ID = '109212785509656396'

